retrace-client: Port to libsoup3
abrt/abrt pull request #1609
Opened 2022-05-27 08:44 UTC by mcrha

This is related to the effort of moving to libsoup3, tracked here:
https://gitlab.gnome.org/GNOME/libsoup/-/issues/218

and a Fedora discussion started here:
https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/JAQJ5WJQ6U6IZ3BZAZ5AM3VMMQCNOA7G/

Please note that the change needs testing, I do not know how you do that without touching real servers. The code only builds without warnings.

2022-05-31 10:53 UTC, mgrabovsky requested changes
Fantastic! Thanks for the PR. The code looks fine at a glance, I've only pointed out a few exceedingly long lines. I'll test it functionally later today.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
As above, wrap this line, please.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
Wrap this line, please.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
Wrap this line, please.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
Wrap this line, too, please.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
Wrap this line, please.

2022-05-31 10:53 UTC, mgrabovsky commented on src/plugins/abrt-retrace-client.c
> +                          response_code, response ? (int) g_bytes_get_size(response) : 0, response ? (const gchar *)g_bytes_get_data(response, NULL) : "");
Wrap this line, please.

2022-05-31 16:25 UTC, mcrha commented
Sure, I can wrap those long lines. I'll wait for the functional testing before doing the changes, in case you'll find any problem(s) with the patch (it's likely).

By the way, thinking of it, is the retrace-client loaded into any other process or it runs on its own? I made this change to make gnome-shell run, but maybe the problem I faced was not related to the port. I'm not sure. If the retrace-server (aka the code loading libsoup) runs in the abrt space only, then this can be used (if working) directly, otherwise a compile time switch to use libsoup2 or libsoup3 will be needed, to match the libsoup version of the process the retrace-client is loaded into. I did not think of this option before.

2022-06-02 06:21 UTC, mcrha commented
I went ahead and made the requested changes. I wrapped few more lines. I did not wrap all exceeding the 85, because that would affect readability, from my point of view (see the "X-Task..." headers, only the header name would be on the next line, which is ugly).

My approach for the above claims was to split the lines and to change the indentation level. If you think it's a bad idea I can do the "use variables" approach, though the current one is neater.

2022-08-17 08:39 UTC, mgrabovsky commented
I'm so sorry, this has sort of fallen through the cracks. I'll make sure this moves forward today.

retrace-client always runs standalone so there should be no need for handling the older version.

2022-08-17 09:03 UTC, mgrabovsky approved these changes
Looks fine to me.

2022-08-17 09:03 UTC, merged